<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ParallelScan.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
  
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="Reko.Decompiler.Runtime" Version="0.12.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scanner\parallel-scan.csproj" />
  </ItemGroup>

</Project>
